const v = {
  id: 46088460,
  node_id: "MDEwOlJlcG9zaXRvcnk0NjA4ODQ2MA==",
  name: "swagger-react",
  full_name: "evanrs/swagger-react",
  private: false,
  owner: {
    login: "evanrs",
    id: 297455,
    node_id: "MDQ6VXNlcjI5NzQ1NQ==",
    avatar_url: "https://avatars.githubusercontent.com/u/297455?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/evanrs",
    html_url: "https://github.com/evanrs",
    followers_url: "https://api.github.com/users/evanrs/followers",
    following_url: "https://api.github.com/users/evanrs/following{/other_user}",
    gists_url: "https://api.github.com/users/evanrs/gists{/gist_id}",
    starred_url: "https://api.github.com/users/evanrs/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/evanrs/subscriptions",
    organizations_url: "https://api.github.com/users/evanrs/orgs",
    repos_url: "https://api.github.com/users/evanrs/repos",
    events_url: "https://api.github.com/users/evanrs/events{/privacy}",
    received_events_url: "https://api.github.com/users/evanrs/received_events",
    type: "User",
    site_admin: false,
  },
  html_url: "https://github.com/evanrs/swagger-react",
  description: "Generate static html pages with React from swagger json",
  fork: false,
  url: "https://api.github.com/repos/evanrs/swagger-react",
  forks_url: "https://api.github.com/repos/evanrs/swagger-react/forks",
  keys_url: "https://api.github.com/repos/evanrs/swagger-react/keys{/key_id}",
  collaborators_url:
    "https://api.github.com/repos/evanrs/swagger-react/collaborators{/collaborator}",
  teams_url: "https://api.github.com/repos/evanrs/swagger-react/teams",
  hooks_url: "https://api.github.com/repos/evanrs/swagger-react/hooks",
  issue_events_url: "https://api.github.com/repos/evanrs/swagger-react/issues/events{/number}",
  events_url: "https://api.github.com/repos/evanrs/swagger-react/events",
  assignees_url: "https://api.github.com/repos/evanrs/swagger-react/assignees{/user}",
  branches_url: "https://api.github.com/repos/evanrs/swagger-react/branches{/branch}",
  tags_url: "https://api.github.com/repos/evanrs/swagger-react/tags",
  blobs_url: "https://api.github.com/repos/evanrs/swagger-react/git/blobs{/sha}",
  git_tags_url: "https://api.github.com/repos/evanrs/swagger-react/git/tags{/sha}",
  git_refs_url: "https://api.github.com/repos/evanrs/swagger-react/git/refs{/sha}",
  trees_url: "https://api.github.com/repos/evanrs/swagger-react/git/trees{/sha}",
  statuses_url: "https://api.github.com/repos/evanrs/swagger-react/statuses/{sha}",
  languages_url: "https://api.github.com/repos/evanrs/swagger-react/languages",
  stargazers_url: "https://api.github.com/repos/evanrs/swagger-react/stargazers",
  contributors_url: "https://api.github.com/repos/evanrs/swagger-react/contributors",
  subscribers_url: "https://api.github.com/repos/evanrs/swagger-react/subscribers",
  subscription_url: "https://api.github.com/repos/evanrs/swagger-react/subscription",
  commits_url: "https://api.github.com/repos/evanrs/swagger-react/commits{/sha}",
  git_commits_url: "https://api.github.com/repos/evanrs/swagger-react/git/commits{/sha}",
  comments_url: "https://api.github.com/repos/evanrs/swagger-react/comments{/number}",
  issue_comment_url: "https://api.github.com/repos/evanrs/swagger-react/issues/comments{/number}",
  contents_url: "https://api.github.com/repos/evanrs/swagger-react/contents/{+path}",
  compare_url: "https://api.github.com/repos/evanrs/swagger-react/compare/{base}...{head}",
  merges_url: "https://api.github.com/repos/evanrs/swagger-react/merges",
  archive_url: "https://api.github.com/repos/evanrs/swagger-react/{archive_format}{/ref}",
  downloads_url: "https://api.github.com/repos/evanrs/swagger-react/downloads",
  issues_url: "https://api.github.com/repos/evanrs/swagger-react/issues{/number}",
  pulls_url: "https://api.github.com/repos/evanrs/swagger-react/pulls{/number}",
  milestones_url: "https://api.github.com/repos/evanrs/swagger-react/milestones{/number}",
  notifications_url:
    "https://api.github.com/repos/evanrs/swagger-react/notifications{?since,all,participating}",
  labels_url: "https://api.github.com/repos/evanrs/swagger-react/labels{/name}",
  releases_url: "https://api.github.com/repos/evanrs/swagger-react/releases{/id}",
  deployments_url: "https://api.github.com/repos/evanrs/swagger-react/deployments",
  created_at: "2015-11-12T23:57:53Z",
  updated_at: "2016-03-30T01:27:53Z",
  pushed_at: "2015-11-13T00:05:56Z",
  git_url: "git://github.com/evanrs/swagger-react.git",
  ssh_url: "git@github.com:evanrs/swagger-react.git",
  clone_url: "https://github.com/evanrs/swagger-react.git",
  svn_url: "https://github.com/evanrs/swagger-react",
  homepage: null,
  size: 0,
  stargazers_count: 3,
  watchers_count: 3,
  language: "JavaScript",
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  forks_count: 0,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 0,
  license: {
    key: "apache-2.0",
    name: "Apache License 2.0",
    spdx_id: "Apache-2.0",
    url: "https://api.github.com/licenses/apache-2.0",
    node_id: "MDc6TGljZW5zZTI=",
  },
  allow_forking: true,
  is_template: false,
  topics: [],
  visibility: "public",
  forks: 0,
  open_issues: 0,
  watchers: 3,
  default_branch: "master",
};
